<tr class="ask">
                      <td align=left width="300" height="30"><a class=b2 href="[field:arcurl/]" class="tag_title_link">[field:title/]..</a></td>
                    </tr>
                    <tr class="answer">
                      <td align=left width="300" height="30"><a class=b2 href="[field:arcurl/]" class="tag_title_link">[field:description function="cn_substr(@me,150)"/]...</a></td>
                    </tr>