<?php
$z[0]=Array("channel","\r\n        <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n       ",88,204);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[1]=Array("global","",351,377);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",443,465);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",495,516);
$z[3][4]['name']="cfg_cz";
$z[4]=Array("global","",591,612);
$z[4][4]['name']="cfg_dz";
$z[5]=Array("global","",642,666);
$z[5][4]['name']="cfg_email";

?>