<?php
$z[0]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",150,276);
$z[0][4]['type']="son";
$z[0][4]['row']="10";
$z[1]=Array("global","",456,478);
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",505,526);
$z[2][4]['name']="cfg_cz";
$z[3]=Array("global","",552,576);
$z[3][4]['name']="cfg_email";
$z[4]=Array("global","",602,623);
$z[4][4]['name']="cfg_dz";

?>