<?php
$z[0]=Array("global","",117,145);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",158,177);
$z[1][4]['name']="title";
$z[2]=Array("global","",178,204);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",245,274);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",398,433);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",654,683);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n      <li><a href=\"[field:arcurl/]\">[field:title/]...<span> [[field:pubdate function=\"GetDateTimeMK(@me)\" /]]</span></a></li>\r\n      ",760,932);
$z[6][4]['pagesize']="10";
$z[7]=Array("pagelist","",969,1022);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[8]=Array("include","",1049,1084);
$z[8][4]['filename']="left.htm";
$z[9]=Array("include","",1086,1121);
$z[9][4]['filename']="foot.htm";

?>