<?php
$z[0]=Array("global","",117,145);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",158,177);
$z[1][4]['name']="title";
$z[2]=Array("global","",178,204);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",245,274);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",400,435);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",672,701);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n        <div class=\"leftGCsubLine\"><a href=\"[field:arcurl/]\"> <img src=\"[field:picname/]\" width=\"218\" height=\"143\">\r\n          <div class=\"GCText\">\r\n            <h1>[field:title/]</h1>\r\n            <p>[field:description function=\"cn_substr(@me,300)\"/]</p>\r\n          </div>\r\n          </a> </div>\r\n        ",751,1095);
$z[6][4]['pagesize']="4";
$z[7]=Array("pagelist","",1125,1178);
$z[7][4]['listitem']="index,end,pre,next,pageno";

?>